FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
        avrdude \
        avrdude-doc \
        binutils-avr \
        avr-libc \
        gcc-avr \
        gdb-avr \
        make \
        git \
        vim

RUN git clone https://github.com/hexagon5un/AVR-Programming
